allowBuilds:
  sharp: false
  unrs-resolver: false
ignoredBuiltDependencies:
  - sharp
  - unrs-resolver
minimumReleaseAge: 0
onlyBuiltDependencies:
  - "@minhvhdev/hf-db-sdk@https://codeload.github.com/minhvhdev/hf-db-sdk/tar.gz/4870e48245913a82b00deefc30278a5f8280c074"
